affects: ListVAProxy (value = None) with 0 subscribers
binning: VigilantAttributeProxy (value = None px) with 0 subscribers
children: VigilantAttributeProxy (value = None) with 0 subscribers
dependencies: VigilantAttributeProxy (value = None) with 0 subscribers
depthOfField: VigilantAttributeProxy (value = None m) with 0 subscribers
exposureTime: VigilantAttributeProxy (value = None s) with 0 subscribers
fanSpeed: VigilantAttributeProxy (value = None ) with 0 subscribers
gain: VigilantAttributeProxy (value = None ) with 0 subscribers
pixelSize: VigilantAttributeProxy (value = None m) with 0 subscribers
pointSpreadFunctionSize: VigilantAttributeProxy (value = None px) with 0 subscribers
readoutRate: VigilantAttributeProxy (value = None Hz) with 0 subscribers
resolution: VigilantAttributeProxy (value = None px) with 0 subscribers
state: VigilantAttributeProxy (value = None) with 0 subscribers
targetTemperature: VigilantAttributeProxy (value = None °C) with 0 subscribers
temperature: VigilantAttributeProxy (value = None °C) with 0 subscribers
translation: VigilantAttributeProxy (value = None px) with 0 subscribers